# ??? ??
spring.application.name=RecommendSystem
spring.config.import=optional:file:.env[.properties]
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false


#spring.devtools.restart.exclude=uploads/**
#spring.devtools.livereload.enabled=true
spring.devtools.livereload.enabled=false
spring.devtools.restart.enabled=false

spring.freemarker.cache=false
management.endpoints.web.exposure.include=*

# ????? ??
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.type-aliases-package=shop/RecommendSystem/dto
mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# ?? ??
logging.level.org.apache.ibatis=DEBUG
logging.level.org.mybatis=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.web=DEBUG

#?? ?? ??
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# db ?? ??
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}

# redis
spring.data.redis.host=${redis_host}
spring.data.redis.port=${redis_port}
spring.data.redis.password=${redis_password}

# ?? ??
project_path = ${project_path}

## ?? ?? ??
connectPath = ${connectPath}
resourcePath=${resourcePath}

## ?? api
fastApiUrl=${fastApi_url}
hostInfo=http://localhost:8080

